version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: fortuna_imperatrix_mundi_db
    environment:
      MYSQL_ROOT_PASSWORD: J88d44Jq5ekG
      MYSQL_DATABASE: fortuna_imperatrix_mundi
    ports:
      - "5433:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: